trigger:
- main

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
  maxParallel: 2

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
- script: python3 -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'
- script: df -h
  displayName: 'disk'
