trigger:
- main

pool:
  vmImage: "ubuntu-latest"

container: ubuntu:21.04

steps:
- script: cat /etc/os-release
  displayName: 'os'
- script: apt list --installed
  displayName: 'apt list'
- script: df -h
  displayName: 'disk'
