trigger:
- main

pool:
  vmImage: "ubuntu-latest"

# container: buildpack-deps:jammy

steps:
- script: whoami
  displayName: 'whoami'
- script: cat /etc/os-release
  displayName: 'os'
- script: apt list --installed
  displayName: 'apt list'
- script: df -h
  displayName: 'disk'
- script: cat /proc/cpuinfo
  displayName: 'cpuinfo'
- script: curl -sL "https://github.com/rokibhasansagar/slimhub_actions/raw/main/cleanup.sh" | bash
  displayName: 'SLIMHUB'
